name: Publicação automática
on:
  # nosso script será executado sempre quando houver push e pull request nas branches destacadas abaixo
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    # sistema operacional da máquina que o Github irá disponibilizar para rodar o nosso script
    runs-on: ubuntu-latest

    # aqui é iniciado o passo a passo para realizar o processo de publicação
    steps:
      - uses: actions/checkout@v3

      - name: Cria um arquivo temporário para a chave privada 
        run: |
               echo "${{ secrets.KEY }}" > /tmp/private_key
               chmod 600 /tmp/private_key
               
      - name: Publicando...
        run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               # Criando o diretório da aplicação \
               sudo mkdir -p /home/ubuntu/appdemo1 && sudo chown -R ubuntu:ubuntu /home/ubuntu/appdemo1 \

               # Transferindo os arquivos da aplicação
               scp -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ${{ github.workspace }}/* ubuntu@${{ secrets.HOST }}:/home/ubuntu/appdemo1

      - name: Limpa o arquivo de chave privada após uso
        run: |
           rm /tmp/private_key
