name: Publicação automática
on:
  # nosso script será executado sempre quando houver push e pull request nas branches destacadas abaixo
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    # sistema operacional da máquina que o Github irá disponibilizar para rodar o nosso script
    runs-on: ubuntu-latest

    # aqui é iniciado o passo a passo para realizar o processo de publicação
    steps:
      - uses: actions/checkout@v3
      - name: Restaurando os pacotes/dependências NODE
        run: npm install 
      - name: Conectar via SSH no servidor de Produção e transferir os arquivos resultantes da compilação
        env:
          CAMINHO_PROJETO_PASTA_COMPILACAO: ${{ github.workspace }}/build
        run: |
             scp -i ${{ secrets.KEY }} -r ${CAMINHO_PROJETO_PASTA_COMPILACAO}/* ubuntu@${{ secrets.HOST }}:/home/ubuntu/appdemo1

