name: Publicação automática
on:
  # nosso script será executado sempre quando houver push e pull request nas branches destacadas abaixo
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    # sistema operacional da máquina que o Github irá disponibilizar para rodar o nosso script
    runs-on: ubuntu-latest

    # aqui é iniciado o passo a passo para realizar o processo de publicação
    steps:
      - uses: actions/checkout@v3
      - name: Restaurando os pacotes/dependências NODE
        run: npm install 
      - name: Conectar via SSH no servidor de Produção e transferir os arquivos resultantes da compilação
        run: |
           # Cria um arquivo temporário para a chave privada
           echo "${{ secrets.KEY }}" 
           chmod 600 /tmp/private_key /tmp/private_key
           # Usa o arquivo temporário para a conexão SSH
           ssh -i /tmp/private_key ubuntu@${{ secrets.HOST }}
           # Opcional: Limpa o arquivo de chave privada após uso
           rm /tmp/private_key

